'use strict';
const serviceData=[
 {id:'umum',group:'umum',tag:'PELAYANAN DASAR',name:'Pemeriksaan Umum',text:'Informasi pemeriksaan kesehatan dasar dan alur pelayanan primer.',icon:'ic-heart'},
 {id:'kia',group:'keluarga',tag:'IBU & ANAK',name:'Kesehatan Ibu dan Anak',text:'Informasi kebutuhan layanan ibu, bayi, dan tumbuh kembang.',icon:'ic-baby'},
 {id:'gigi',group:'umum',tag:'KESEHATAN GIGI',name:'Gigi dan Mulut',text:'Informasi pemeriksaan, konsultasi, dan edukasi kesehatan gigi.',icon:'ic-shield'},
 {id:'ckg',group:'preventif',tag:'DETEKSI DINI',name:'Cek Kesehatan Gratis',text:'Informasi sasaran, persiapan, dan alur program CKG.',icon:'ic-activity'},
 {id:'lab',group:'penunjang',tag:'PENUNJANG',name:'Pemeriksaan Laboratorium',text:'Informasi pemeriksaan pendukung jika layanan tersedia.',icon:'ic-chart'},
 {id:'obat',group:'penunjang',tag:'PENUNJANG',name:'Farmasi & Informasi Obat',text:'Panduan pelayanan obat dan edukasi penggunaan yang tepat.',icon:'ic-doc'}
];
let selectedGroup='all'; let search='';
const icon=(name,small=false)=>`<svg class="icon ${small?'icon-sm':''}" aria-hidden="true"><use href="#${name}"/></svg>`;
function renderServices(){
 const result=serviceData.filter(s=>(selectedGroup==='all'||s.group===selectedGroup)&&(`${s.name} ${s.text} ${s.tag}`.toLowerCase().includes(search.toLowerCase())));
 document.getElementById('service-grid').innerHTML=result.map(s=>`<article class="svc-card"><div class="svc-icon">${icon(s.icon)}</div><span class="svc-tag">${s.tag}</span><h3>${s.name}</h3><p>${s.text}</p><div class="svc-meta">${icon('ic-clock',true)} Jadwal dan ketersediaan menunggu verifikasi</div><button class="svc-link" data-service="${s.id}">Detail layanan ${icon('ic-arrow',true)}</button></article>`).join('');
 document.getElementById('service-count').textContent=`${result.length} layanan konseptual`;
 document.getElementById('service-empty').hidden=result.length!==0;
 document.querySelectorAll('[data-service]').forEach(btn=>btn.addEventListener('click',()=>showDetail(btn.dataset.service)));
}
function showDetail(id){const s=serviceData.find(x=>x.id===id); const panel=document.getElementById('service-detail');if(!s)return;panel.hidden=false;panel.innerHTML=`<div class="detail-top"><div><span class="overline">DETAIL KONSEPTUAL</span><h3>${s.name}</h3></div><button id="detail-close" aria-label="Tutup detail">×</button></div><p>${s.text}</p><div class="detail-fields"><div><b>Sasaran</b><span>Menunggu dokumen pelayanan resmi.</span></div><div><b>Persyaratan</b><span>Belum diverifikasi.</span></div><div><b>Jam dan lokasi</b><span>Belum diverifikasi.</span></div><div><b>Tarif / JKN</b><span>Menunggu ketentuan resmi.</span></div><div><b>Alur</b><span>Menunggu standar pelayanan.</span></div><div><b>Pembaruan terakhir</b><span>Belum dipublikasikan.</span></div></div><small>Contoh tata letak saja; jangan dipakai sebagai panduan kunjungan pasien.</small>`;document.getElementById('detail-close').onclick=()=>{panel.hidden=true}; panel.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function navigate(route,scroll=true){if(!['home','services','programs','insights','public','office'].includes(route))route='home'; document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${route}`));document.querySelectorAll('.navigation [data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===route));document.getElementById('navigation').classList.remove('open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');document.getElementById('menu-toggle').setAttribute('aria-label','Buka menu');document.title=`${{home:'Beranda',services:'Layanan',programs:'Program Kesehatan',insights:'Kesehatan Wilayah',public:'Informasi Publik',office:'Kantor Virtual — Demo'}[route]} | Malimpung Health Hub — Konsep`;history.replaceState(null,'',`#${route}`);if(scroll)window.scrollTo({top:0,behavior:'instant'});}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navigate(b.dataset.go)}));
document.getElementById('menu-toggle').addEventListener('click',()=>{const n=document.getElementById('navigation'),isOpen=n.classList.toggle('open');document.getElementById('menu-toggle').setAttribute('aria-expanded',String(isOpen));document.getElementById('menu-toggle').setAttribute('aria-label',isOpen?'Tutup menu':'Buka menu');});
document.getElementById('service-search').addEventListener('input',e=>{search=e.target.value;renderServices()});document.getElementById('service-reset').addEventListener('click',()=>{search='';selectedGroup='all';document.getElementById('service-search').value='';document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('selected',b.dataset.category==='all'));renderServices();});document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{selectedGroup=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('selected',x===b));renderServices()}));
const topicText={ckg:['Cakupan pemeriksaan CKG','Indikator diterbitkan setelah pembilang, penyebut, dan periode ditetapkan.'],kia:['Kesehatan ibu dan anak','Informasi KIA akan ditampilkan sesuai indikator yang telah ditetapkan dan hak publikasi.'],ptm:['Pemantauan skrining PTM','Temuan skrining tidak otomatis merupakan diagnosis ataupun prevalensi penduduk.'],pws:['Pelayanan per wilayah','Peta dan daftar desa baru aktif setelah batas wilayah kerja diverifikasi.']};
document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-topic]').forEach(x=>x.classList.toggle('selected',x===b));const t=topicText[b.dataset.topic];document.getElementById('topic-title').textContent=t[0];document.getElementById('topic-desc').textContent=t[1];}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('entered');observer.unobserve(e.target)}}),{threshold:.05});document.querySelectorAll('.section-heading,.quick,.program-mosaic,.eco-grid,.story-grid,.ed-big,.ed-list,.closing-grid').forEach(el=>observer.observe(el));
renderServices();navigate(location.hash.slice(1)||'home',false);
